### ISSUE TITLE
Strange results when querying relationships

### ISSUE THREAD

**Issue by mdpoulter** [staudenmeir/laravel-adjacency-list#23] opened 2020-03-22 12:00 UTC
Hi @staudenmeir 

Thanks so much for the great package!

I have run into a problem that I'm hoping is just something that I'm missing... Essentially, I have a `Page` model which utilises your package, and has a `status` field to indicate whether it is enabled or not.

I am now trying to to get a list of all pages which are enabled (where `status = 1`) where all their ancestors are also enabled. My gut feeling was to use a query such as this:

```php
Page::whereDoesntHave('ancestorsAndSelf', function ($query) {
    $query->where('status', 0);
})->get();
```

This returns a list of all enabled pages, but does not filter pages who have ancestors who are disabled. For example, given the following pages:

```php
[
     [
       "id" => 1,
       "parent_id" => null,
       "status" => 1,
     ],
     [
       "id" => 2,
       "parent_id" => 1,
       "status" => 0,
     ],
     [
       "id" => 3,
       "parent_id" => 2,
       "status" => 1,
     ],
]
```

I would expect my query above to return only the page with `id` of `1`, but instead it returns both pages `1` and `3`.

Am I missing something, or is this a limitation? If it's the latter, do you have a suggestion for how I could produce such a list?

Thanks so much!

**Comment by staudenmeir** [comment] 2020-03-22 16:56
Interesting issue. I can reproduce it on MySQL, but I'm getting the correct result on PostgreSQL.

I'll look into it.

**Comment by staudenmeir** [comment] 2020-03-22 17:14
As a workaround, here is an equivalent query that returns the correct result:

```php
Page::whereDoesntHave('ancestors', function ($query) {
    $query->where('status', 0);
})->where('status', 1)->get();
```

**Comment by mdpoulter** [comment] 2020-03-22 18:21
Thanks for the workaround! It seems to work for 3 levels, but not for 4 unfortunately, which is strange. For example, given the following data:

```php
[
     [
       "id" => 1,
       "parent_id" => null,
       "status" => 1,
     ],
     [
       "id" => 2,
       "parent_id" => 1,
       "status" => 0,
     ],
     [
       "id" => 3,
       "parent_id" => 2,
       "status" => 1,
     ],
     [
       "id" => 4,
       "parent_id" => 3,
       "status" => 1,
     ],
]
```

It returns both pages `1` and `4`. It seems that the `where` inside the anonymous function is only looking at the direct ancestor, but not all recursive ones.

Thanks for looking into this!

**Comment by staudenmeir** [comment] 2020-03-22 18:40
Weird, looks like a bigger issue. Again, the query works on PostgreSQL.

**Comment by mdpoulter** [comment] 2020-03-22 18:45
Yeah, I'm stuck on MySQL at the moment, but may look into PostgreSQL if it doesn't look fixable.

**Comment by staudenmeir** [comment] 2020-03-22 18:49
I'm working on a bug report to the MySQL team.

**Comment by mdpoulter** [comment] 2020-03-22 19:34
Thank you!

**Comment by staudenmeir** [comment] 2020-03-22 21:11
The bug has been confirmed: https://bugs.mysql.com/bug.php?id=99025

It's a regression,  the query worked in 8.0.16.

**Comment by mdpoulter** [comment] 2020-03-23 07:11
Ah interesting! I'll rollback to 8.0.16 for now then until it's fixed. Thanks for submitting that!

**Comment by staudenmeir** [comment] 2020-03-24 16:40
I'm going to close this since it's not an issue with the package.

**Closed by staudenmeir** 2020-03-24 16:40 UTC

**Comment by staudenmeir** [comment] 2020-07-13 19:41
MySQL 8.0.21 has been released and should fix this bug.
